-- AlterTable
ALTER TABLE "awards" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "backend" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "cloud" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "databases" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "devops" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "education" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "experience" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "files" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "frontend" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "mobile" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "projects" ALTER COLUMN "dt_cadastro" SET DEFAULT CURRENT_TIMESTAMP;
