services:
  postgres:
    container_name: "postgres-dev-portfolio"
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=portfolio
    volumes:
      - portfolio_pg_data:/bitnami/postgresql

volumes:
  portfolio_pg_data:
